### ISSUE TITLE
cfconfig doesnt include Error template settings in exported json

### ISSUE THREAD

**Issue by sdwebguy** [Ortus-Solutions/commandbox-cfconfig#2]
I am running Commandbox under Lucee 5.2.4.

`cfconfig export .cfconfig.json`
This produces a json file with my settings.

I went to Lucee Server Admin, under Settings / Error, and changed the 505 and 400 settings to use a different cfm from the dropdown. I saved the changes.

`cfconfig export .cfconfig2.json`
Does not include anything different in the file, and no reference to my changed setting.

**Comment by bdw429s** [comment]
That's because those settings aren't supported yet :)   Note, we're using JIRA for CFConfig tickets.  I've re-created your ticket here: https://ortussolutions.atlassian.net/browse/CFCONFIG-7

Please feel free to contribute or sponsor this fix!
