### ISSUE TITLE
Add ability to set debugging on/off

### ISSUE THREAD

**Issue by cybersonic** [Ortus-Solutions/commandbox-cfconfig#7]
And maybe more of the settings for Lucee (set template, set SQL logging etc etc) 

If you could point the way I might be able to implement it.

**Comment by bdw429s** [comment]
I just recently added most all the debugging setting I could find for Adobe (paid work for a client).  There's a bunch of commented out lines in this file that are some Lucee debugging settings I made note of early on but hadn't implemented:

https://github.com/Ortus-Solutions/cfconfig/blob/master/models/BaseConfig.cfc#L384-L391

Here's most of the debugging settings that are already implemented (most are Adobe-centric) 

https://github.com/Ortus-Solutions/cfconfig/blob/master/models/BaseConfig.cfc#L296-L353

Basically, each missing Lucee debugging setting needs to be checked against that list to see if there is a suitable setting name we can re-use.  For any debugging settings that are unique to Lucee, we need to add additional properties into the `BaseConfig.cfc` for each of them with the proper type and comment that clarifies what they are. 

As far as adding a new setting in, there are three places the code needs touched for every setting:

1. Added as a property to `BaseConfig.cfc` (linked to above)
2. Add logic to "read" the setting in the `BaseLucee.cfc` file 
3. Add logic to "write" the setting in the`BaseLucee.cfc` file 

As an example, here are the 3 bits of code for a random setting:
 
Global definition of the setting:
https://github.com/Ortus-Solutions/cfconfig/blob/master/models/BaseConfig.cfc#L108

Logic for Lucee to read the setting:
https://github.com/Ortus-Solutions/cfconfig/blob/master/models/BaseLucee.cfc#L187

Logic for Lucee to write the setting:
https://github.com/Ortus-Solutions/cfconfig/blob/master/models/BaseLucee.cfc#L562

Logic for Adobe to read the setting:
https://github.com/Ortus-Solutions/cfconfig/blob/master/models/BaseAdobe.cfc#L133

Logic for Adobe to write the setting:
https://github.com/Ortus-Solutions/cfconfig/blob/master/models/BaseAdobe.cfc#L611

It's also worth noting, this all happens in the main cfconfig repo.  This repo is only for the CommandBox CLI portion of CFConfig which only includes the code for the commands and CommandBox module but not the core services which are standalone.

**Comment by bdw429s** [comment]
Also, I need to disable the issue tracker on this repo.  Here is the JIRA we use:
https://ortussolutions.atlassian.net/projects/CFCONFIG/issues/CFCONFIG-17?filter=allissues

**Comment by bdw429s** [comment]
Here's the new ticket, I'm closing this so I can disable the issue tracker from Github,.
